### ISSUE TITLE
signaturePadComponent is not defined

### ISSUE THREAD

**Issue by dormeljon** [savannabits/filament-signature-pad#2]
after installing the plugin (on top of the stand alone filamentphp fors builder plugin), the signature pad shows but not functional.
errors show in the console:
Uncaught ReferenceError: signaturePadComponent is not defined

**Comment by coolsam726** [comment]
This could mean that the JS was not registered before alpine.js. Please share steps to reproduce.

**Comment by dormeljon** [comment]
actually i dont see the JS file loading at all.
1. i have custom livewire app (no fillament admin package installed)
2. installed only filamentphp forms plugin
3. all works correctly
4. run composer require savannabits/filament-signature-pad on my app terminal
5. add "SignaturePad::make('signature')" to my form's schema
6. import class (use Savannabits\SignaturePad\Forms\Components\Fields\SignaturePad)
7. previewing page, see the signature pad, that is not functional.
8. see errors on the console "signaturePadComponent is not defined"

**Comment by coolsam726** [comment]
That makes sense. I hadn't factored in the option of loading the package without Filament. The javascript is loaded by Filament. Let me see how I can support using it outside Filament.

**Comment by alexbirtwell** [comment]
+1 same issue as @dormeljon using the package with Filament Form Build outside of filament

**Comment by Sirloko** [comment]
same issue, any luck?

**Comment by dormeljon** [comment]
i eventually ended up with creating my own signature pad with some changes that works for me. 
happy to share:
1. create a blade component **sig-pade.blade.php**

<x-dynamic-component :component="$getFieldWrapperView()" :id="$getId()" :label="$getLabel()" :label-sr-only="$isLabelHidden()" :helper-text="$getHelperText()"
    :hint="$getHint()" :hint-action="$getHintAction()" :hint-color="$getHintColor()" :hint-icon="$getHintIcon()" :required="$isRequired()" :state-path="$getStatePath()">
    <div>
        <div wire:ignore x-data="{
            state: $wire.entangle('{{ $getStatePath() }}').defer,
            signaturePadId: $id('signature'),
            signaturePad: null,
            signature: @entangle($getStatePath()).defer,
            ratio: null,
            init() {
                this.resizeCanvas(); // resize canvas before initializing
                this.signaturePad = new SignaturePad(this.$refs.canvas);
                if (this.signature) {
                    // pass ratio when loading a saved signature
                    this.signaturePad.fromDataURL(this.signature, { ratio: this.ratio });
                }
        
                //listen to endStroke event
                this.signaturePad.addEventListener('endStroke', () => {
                    this.save();
                });
        
        
            },
            clear() {
                this.signaturePad.clear();
                this.signature = null;
                // console.log(this.signature);
        
            },
            // The resize canvas function https://github.com/szimek/signature_pad#tips-and-tricks﻿
            resizeCanvas() {
                this.ratio = Math.max(window.devicePixelRatio || 1, 1);
                this.$refs.canvas.width = this.$refs.canvas.offsetWidth * this.ratio;
                this.$refs.canvas.height = this.$refs.canvas.offsetHeight * this.ratio;
                this.$refs.canvas.getContext('2d').scale(this.ratio, this.ratio);
            },
            save() {
                this.signature = this.signaturePad.toDataURL();
                // console.log(this.signature);
            }
        }" @resize.window="resizeCanvas" class="mt-4">

            <canvas x-ref="canvas" class="w-full h-full border-2 border-gray-300 border-dashed rounded-md" width="600"
                height="400"></canvas>

            <div class="flex mt-2 space-x-2 space-x-reverse">
                <a href="#" x-on:click.prevent="clear()" class="text-sm font-medium text-gray-700 underline">
                    Delete
                </a>
            </div>

        </div>

        
        @pushonce('scripts')
            <script src="https://cdn.jsdelivr.net/npm/signature_pad@4.0.0/dist/signature_pad.umd.min.js"></script>
        @endpushonce

    </div>
</x-dynamic-component>

3. then on the livewire comonent use "SigPad::make('signature')"

**Comment by Sirloko** [comment]
Thanks @dormeljon 

I just tried this and it worked.

ran "npm install --save signature_pad"
Then i updated my app.js with this
https://github.com/savannabits/filament-signature-pad/blob/main/resources/js/signature-pad.js

**Comment by nessimabadi** [comment]
HI @dormeljon , how did you get this to work?
Thanks for the help

**Comment by sanadpay** [comment]
@Sirloko 
do you use the signature pad in filament? 
I have tried you way but didn't work for me

**Comment by Elzakzouk** [comment]
@Sirloko
do you use the signature pad in filament?
I have tried you way but didn't work for me

**Comment by nessimabadi** [comment]
Hi @coolsam726 

Is there any way to use this without the Admin Panel component of Filament. Just using the Forms library.

Thanks for this amazing package
