### ISSUE TITLE
Signature pad breaks when making Cards in the form

### ISSUE THREAD

**Issue by DevMushref** [savannabits/filament-signature-pad#3]
I created a Card schema:

```
Forms\Components\Card::make()->schema([
                    Forms\Components\TextInput::make('lf_number')
                        ->required()
                        ->label('LF #')
                        ->default(DB::table('lost_found_items')->get('lf_number')->max('lf_number') + 1)
                        ->disabled()
                        ->hiddenOn('edit'),
                    Forms\Components\TextInput::make('item_name')
                        ->required(),
                    Forms\Components\TextInput::make('found_by')
                        ->required(),
                    Forms\Components\TextInput::make('claimed_by')
                        ->required(),
                ])->columns(4),
```

And when I include `SignaturePad::make('collector_signature')->required(),` either outside or inside the card it breaks, like so:

![ezgif com-gif-maker](https://user-images.githubusercontent.com/25293489/210740428-0637be33-7ce9-4fb8-bd0c-0bc9d54ed668.gif)

**Comment by Sirloko** [comment]
I have the same issue, any fix yet?

**Comment by DevMushref** [comment]
@Sirloko Sadly no, waiting for the developer.

**Comment by masehitam** [comment]
I noticed there are some differences about the size of the canvas.
normal:
`
<canvas
    x-ref="canvas"
    class="w-full h-full border-2 border-gray-300 border-dashed rounded-md"
    style="touch-action: none; user-select: none"
    width="2026"
    height="158"
></canvas>
`
when size changes:
`
<canvas
    x-ref="canvas"
    class="w-full h-full border-2 border-gray-300 border-dashed rounded-md"
></canvas>

`
in the modal:
`
<canvas
    x-ref="canvas"
    class="w-full h-full border-2 border-gray-300 border-dashed rounded-md"
    style="touch-action: none; user-select: none"
    width="0"
    height="0"
></canvas>
`

sorry didn't help much

**Comment by iamkatohitoshi** [comment]
> I created a Card schema:
> 
> ```
> Forms\Components\Card::make()->schema([
>                     Forms\Components\TextInput::make('lf_number')
>                         ->required()
>                         ->label('LF #')
>                         ->default(DB::table('lost_found_items')->get('lf_number')->max('lf_number') + 1)
>                         ->disabled()
>                         ->hiddenOn('edit'),
>                     Forms\Components\TextInput::make('item_name')
>                         ->required(),
>                     Forms\Components\TextInput::make('found_by')
>                         ->required(),
>                     Forms\Components\TextInput::make('claimed_by')
>                         ->required(),
>                 ])->columns(4),
> ```
> 
> And when I include `SignaturePad::make('collector_signature')->required(),` either outside or inside the card it breaks, like so:
> 
> ![ezgif com-gif-maker](https://user-images.githubusercontent.com/25293489/210740428-0637be33-7ce9-4fb8-bd0c-0bc9d54ed668.gif) [ ![ezgif com-gif-maker](https://user-images.githubusercontent.com/25293489/210740428-0637be33-7ce9-4fb8-bd0c-0bc9d54ed668.gif) ](https://user-images.githubusercontent.com/25293489/210740428-0637be33-7ce9-4fb8-bd0c-0bc9d54ed668.gif) [ ](https://user-images.githubusercontent.com/25293489/210740428-0637be33-7ce9-4fb8-bd0c-0bc9d54ed668.gif)

like you, i'm doing a HSE app too. And i'm facing the exact same problem as u did. did u manage to find a fix for it?
