### ISSUE TITLE
Undefined variable $isDownloadDisabled

### ISSUE THREAD

**Issue by Elzakzouk** [savannabits/filament-signature-pad#9]
I am facing Undefined variable $isDownloadDisabled when trying to use the package.

**Comment by ibrahimi3** [comment]
This seems to be coming from the function defined in the blade template "./filament-signature-pad/resources/views/forms/components/fields/signature-pad.blade.php" line 32. Update the function **isDownloadDisabled()** to **isDisabledDownload** as defined in "./filament-signature-pad/src/Forms/Concerns/HasSignaturePadAttributes.php" line 105 and it should be sorted.

**Comment by rabol** [comment]
will there be an official fix ?

**Comment by coolsam726** [comment]
The above merge is the fix and is released in v1.2.0
